title: Justin's nest  
author: Justin
email: suguo@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  In here, you will see the up-to-dated APPs, solving your daily issue with minimum effort.

# social links
twitter_username: your-twitter-handle
github_username:  justinsu2019.github.io

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
